version: "2"

services:
  db:
    image: postgres:12
    volumes:
    - "./data/postgresql:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
    - "127.0.0.1:5439:5432"

  worker:
    build: .
    command: bash
    links:
    - db
    volumes:
    - "./data:/data"
    - ".:/synonames"
    tmpfs:
    - "/tmp"
